INSERT INTO products_location_secondary_archive (
  `Item Number`,
  `1 Location`,
  `1 Loading Required?`,
  `1 Order Point`,
  `2 Location`,
  `2 Loading Required?`,
  `2 Order Point`,
  `3 Location`,
  `3 Loading Required?`,
  `3 Order Point`,
  `4 Location`,
  `4 Loading Required?`,
  `4 Order Point`,
  `5 Location`,
  `5 Loading Required?`,
  `5 Order Point`,
  `6 Location`,
  `6 Loading Required?`,
  `6 Order Point`,
  `7 Location`,
  `7 Loading Required?`,
  `7 Order Point`,
  `8 Location`,
  `8 Loading Required?`,
  `8 Order Point`,
  `10 Location`,
  `10 Loading Required?`,
  `10 Order Point`,
  `11 Location`,
  `11 Loading Required?`,
  `11 Order Point`,
  `12 Location`,
  `12 Loading Required?`,
  `12 Order Point`,
  `13 Location`,
  `13 Loading Required?`,
  `13 Order Point`,
  `14 Location`,
  `14 Loading Required?`,
  `14 Order Point`,
  `15 Location`,
  `15 Loading Required?`,
  `15 Order Point`,
  `16 Location`,
  `16 Loading Required?`,
  `16 Order Point`,
  `17 Location`,
  `17 Loading Required?`,
  `17 Order Point`,
  `18 Location`,
  `18 Loading Required?`,
  `18 Order Point`,
  `19 Location`,
  `19 Loading Required?`,
  `19 Order Point`,
  `20 Location`,
  `20 Loading Required?`,
  `20 Order Point`,
  `21 Location`,
  `21 Loading Required?`,
  `21 Order Point`,
  `90 Location`,
  `90 Loading Required?`,
  `90 Order Point`,
  `valid_from`,
  `valid_to`,
  `op_type`
)
VALUES (
  new.`Item Number`,
  new.`1 Location`,
  new.`1 Loading Required?`,
  new.`1 Order Point`,
  new.`2 Location`,
  new.`2 Loading Required?`,
  new.`2 Order Point`,
  new.`3 Location`,
  new.`3 Loading Required?`,
  new.`3 Order Point`,
  new.`4 Location`,
  new.`4 Loading Required?`,
  new.`4 Order Point`,
  new.`5 Location`,
  new.`5 Loading Required?`,
  new.`5 Order Point`,
  new.`6 Location`,
  new.`6 Loading Required?`,
  new.`6 Order Point`,
  new.`7 Location`,
  new.`7 Loading Required?`,
  new.`7 Order Point`,
  new.`8 Location`,
  new.`8 Loading Required?`,
  new.`8 Order Point`,
  new.`10 Location`,
  new.`10 Loading Required?`,
  new.`10 Order Point`,
  new.`11 Location`,
  new.`11 Loading Required?`,
  new.`11 Order Point`,
  new.`12 Location`,
  new.`12 Loading Required?`,
  new.`12 Order Point`,
  new.`13 Location`,
  new.`13 Loading Required?`,
  new.`13 Order Point`,
  new.`14 Location`,
  new.`14 Loading Required?`,
  new.`14 Order Point`,
  new.`15 Location`,
  new.`15 Loading Required?`,
  new.`15 Order Point`,
  new.`16 Location`,
  new.`16 Loading Required?`,
  new.`16 Order Point`,
  new.`17 Location`,
  new.`17 Loading Required?`,
  new.`17 Order Point`,
  new.`18 Location`,
  new.`18 Loading Required?`,
  new.`18 Order Point`,
  new.`19 Location`,
  new.`19 Loading Required?`,
  new.`19 Order Point`,
  new.`20 Location`,
  new.`20 Loading Required?`,
  new.`20 Order Point`,
  new.`21 Location`,
  new.`21 Loading Required?`,
  new.`21 Order Point`,
  new.`90 Location`,
  new.`90 Loading Required?`,
  new.`90 Order Point`,
  NOW(),
  NOW(),
  'INSERT'
)